/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.OsmNavigator;

public final class R {
    public static final class anim {
        public static final int animations=0x7f040000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int grigio_verde=0x7f070003;
        public static final int nero=0x7f070005;
        public static final int panna=0x7f070004;
        public static final int verde_acido=0x7f070000;
        public static final int verde_erba=0x7f070001;
        public static final int verde_oliva=0x7f070002;
    }
    public static final class drawable {
        public static final int background_image=0x7f020000;
        public static final int blue=0x7f020001;
        public static final int driving=0x7f020002;
        public static final int grey=0x7f020003;
        public static final int icon=0x7f020004;
        public static final int icon2=0x7f020005;
        public static final int lightgrey=0x7f020006;
        public static final int menu_mapinfo=0x7f020007;
        public static final int menu_percorsi=0x7f020008;
        public static final int menu_pexit=0x7f020009;
    }
    public static final class id {
        public static final int MAP=0x7f090000;
        public static final int back=0x7f090007;
        public static final int backgroundImage=0x7f090003;
        public static final int editAutoComplete=0x7f090008;
        public static final int locationDescription=0x7f090001;
        public static final int locationInfo=0x7f090002;
        public static final int mapinfo=0x7f090006;
        public static final int ok=0x7f090005;
        public static final int title=0x7f090004;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int map=0x7f030001;
        public static final int wayselect=0x7f030002;
    }
    public static final class raw {
        public static final int milano=0x7f060000;
        public static final int milano_semplified=0x7f060001;
    }
    public static final class string {
        public static final int app_name=0x7f080001;
        public static final int hello=0x7f080000;
    }
    public static final class xml {
        public static final int som=0x7f050000;
    }
}
